### ISSUE TITLE
Common suggestions om peers.

### ISSUE THREAD

**Issue by mezoni** [DirectMyFile/syscall#2]
Remember the following rules.

1) Memory for binary data allocated from the heap.
2) After when the memory allocated then it also associated with a Dart objects (through registering the peer).
3) Memory freed when Dart object (instance) does not have a references and freed by the garbage collector.

Eg.

``` dart
// final is very suitable
// final means "keep it save"
// int ia[10];
final ia = t["int[10]"].alloc(const []);
```

```
var ia = t["int[10]"].alloc(const []);
// Free (not immediatelly)
ia = null;
```

4) Peer does not propagates on the other binary data.

``` dart
// This data will be dealocated since we don't 'keep it save'
// Program will be corrupted (code 139)
final ip = t["char*"].value = helper.allocString("Boom!");
```

``` dart
// Store before use as a reference
var cp = helper.allocString("Keep it save");
final ip = t["char*"].value = cp;
// Use "cp" and "ip". This is safely
use(ip);
```

``` dart
var heap = [];
var pointers = t["void*[10]"].alloc();
for (...) {
  var obj = type.alloc();
  heap.add(obj);
  pointers[i].value = obj;
}
// Use "pointers" and "referenced" data
use(pointers);
// Free unused objects
heap = null;
```

P.S.

Does not anonymous references!
Be sure to store them safe in the (final) variables or in the lists!

**Comment by azenla** [comment]
Is it not redundant to set heap to null? When the function goes out of scope, it will no longer exist. I'm still a little bit confused as to how memory works with binary_interop. Can you elaborate more?

**Comment by mezoni** [comment]
Of course, redundant.
Only if you allocate a lot of memory.
Web server can have a lot of connections.
If an each instance of the application allocate a lot of memory in a request and do not free it immediately then this is considered bad even in Dart language.
If you allocate not so many memory then you can don't worry about that.

P.S.
That is, if you want `force` deallocation.

**Comment by azenla** [comment]
I see :) Thanks
