### ISSUE TITLE
Breaking changes in "binary_interop" and all the rest, at the lower levels, packages

### ISSUE THREAD

**Issue by mezoni** [DirectMyFile/syscall#5]
Now `binary types` based on the concept of the `headers`.
This new feature (concept) will help reuse existing types.
I want implement `ncurses` but it requires the types from the [standard C library ](https://pub.dartlang.org/packages/libc).

Ask me if you have questions.

**Comment by azenla** [comment]
Thanks :)

**Comment by azenla** [comment]
@mezoni Hello! I now have time to finish this project. Is it possible for you to still allow me to load headers from strings?

**Comment by azenla** [comment]
@mezoni Oops, nevermind, just realized how this works :)

**Comment by mezoni** [comment]
Each developer can provide its own headers (recommended unique eg `package_name/lib_name/header_name.h` or modified original eg. 'strdio,h').
Also developer can (or should) reuse other headers.
Eg.
The `size_t` declared in `stddef.h` in `libc`.

``` c
typedef __UINTPTR_TYPE size_t;
```

**Comment by azenla** [comment]
Nice :)

**Comment by mezoni** [comment]
Example:

``` dart
import 'package:libc/headers.dart';
import 'package:ncurses/headers.dart';
import 'package:managed_library_generator/managed_library_generator.dart';
import 'ncurses_rules.dart';

main() {
  var headers = <String, String>{};
  headers.addAll(LIBC_HEADERS);
  headers.addAll(NCURSES_HEADERS);
  headers["ncurses_generator/bin/header.h"] = _generateHeader(NCURSES_HEADERS);
  var header = headers.keys.last;
  var links = <String>[];
  links.addAll(NCURSES_HEADERS.keys);
  var name = "NCursesLibrary";
  var rules = new NCursesConversionRules();
  var options =
      new ManagedLibraryGeneratorOptions(header: header, headers: headers, links: links, name: name, rules: rules);
  var generator = new ManagedLibraryGenerator();
  var lines = generator.generate(options);
  print(lines.join("\n"));
}

String _generateHeader(Map<String, String> headers) {
  var sb = new StringBuffer();
  for (var key in headers.keys) {
    sb.write("#include <");
    sb.write(key);
    sb.writeln(">");
  }

  return sb.toString();
}
```

**Comment by mezoni** [comment]
All registered headers remains passive (not parsed) until they not used.

1-st case (usage/activation)

``` c
include <header.h>
```

2-nd case (usage/activation)

``` dart
helper.declare(header_name);
```
